---
roles:
  - name: robertdebock.bootstrap
  - name: robertdebock.ca_certificates
  - name: robertdebock.core_dependencies
  - name: robertdebock.container_docs
  - name: robertdebock.mysql
  - name: robertdebock.selinux
  - name: robertdebock.zabbix_repository
collections:
  - name: ansible.posix
  - name: community.mysql
  - name: community.docker
    version: ">=1.2.0,<2"
  - name: community.general
    version: ">=2,<3"
