---
roles:
  - name: robertdebock.bootstrap
  - name: robertdebock.core_dependencies
  - name: robertdebock.container_docs
  - name: robertdebock.mysql
  - name: robertdebock.selinux
  - name: robertdebock.zabbix_repository
collections:
  - name: community.mysql
  - name: ansible.posix
