---

- name: test if zabbix_server_database_user is set correctly
  ansible.builtin.assert:
    that:
      - zabbix_server_database_user is defined
      - zabbix_server_database_user is string
    quiet: yes

- name: test if zabbix_server_database_password is set correctly
  ansible.builtin.assert:
    that:
      - zabbix_server_database_password is defined
      - zabbix_server_database_password is string
    quiet: yes

- name: test if zabbix_server_mysql_connection is set correctly
  ansible.builtin.assert:
    that:
      - zabbix_server_mysql_connection is defined
      - zabbix_server_mysql_connection is string
      - zabbix_server_mysql_connection in [ "network", "socket" ]
    quiet: yes

- name: test if zabbix_server_database_host is set correctly
  ansible.builtin.assert:
    that:
      - zabbix_server_database_host is defined
      - zabbix_server_database_host is string
    quiet: yes
  when:
    - zabbix_server_mysql_connection == "mysql"
