---
- name: test if zabbix_server_database_name is set correctly
  assert:
    that:
    quiet: yes
  when:
    - zabbix_server_database_name is defined

- name: test if zabbix_server_database_user is set correctly
  assert:
    that:
      - zabbix_server_database_user is defined
    quiet: yes

- name: test if zabbix_server_database_password is set correctly
  assert:
    that:
      - zabbix_server_database_password is defined
    quiet: yes

- name: test if zabbix_server_mysql_connection is set correctly
  assert:
    that:
      - zabbix_server_mysql_connection is defined
      - zabbix_server_mysql_connection in [ "network", "socket" ]
    quiet: yes

- name: test if zabbix_server_database_host is set correctly
  assert:
    that:
      - zabbix_server_database_host is defined
    quiet: yes
  when:
    - zabbix_server_mysql_connection == "mysql"
