---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: check if port 10051 is open
      ansible.builtin.wait_for:
        port: 10051
      when:
        - not ci
      vars:
        ci: "{{ lookup('env', 'CI') }}"
