---
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Check if port 10051 is open
      ansible.builtin.wait_for:
        port: 10051
      when:
        - not ci
      vars:
        ci: "{{ lookup('env', 'CI') }}"
