---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: zabbix_server-ubuntu-latest
    image: ubuntu:latest
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        zabbix_server_ignore_docker: no
  lint:
    name: ansible-lint
scenario:
  name: ubuntu-latest
